name: exodide
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: exodide/results:$GITHUB_REF_NAME
          cache-to: type=gha,mode=max,scope=$GITHUB_REF_NAME
          cache-from: type=gha,scope=$GITHUB_REF_NAME
      - run: |
          docker create --name results exodide/results:$GITHUB_REF_NAME
          docker cp results:/dist dist
          docker cp results:/coverage coverage
        name: Extract Results
      - uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist/exodide-*.whl
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage
